services:
  frontend:
    image: sigmaproductions/sigmachatclient:${IMAGE_TAG}
    ports:
      - "3000:3000"
    networks:
      - sigmaChat
    environment:
      - NEXT_PUBLIC_API_HUB=${NEXT_PUBLIC_API_HUB}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_UNTHINKABLE=${NEXT_PUBLIC_UNTHINKABLE}
networks:
  sigmaChat:
    name: sigmaChat




